### ISSUE TITLE
Dead link in README.md

### ISSUE THREAD

**Issue by jajhall** [feldmeier/FilereaderLP#2]
In README.md, the following link is dead

https://www.ibm.com/support/knowledgecenter/SSSA5P_12.7.0/ilog.odms.cplex.help/CPLEX/GettingStarted/topics/tutorials/InteractiveOptimizer/usingLPformat.html

**Comment by feldmeier** [comment]
thanks, fixed by updating link to https://www.ibm.com/docs/en/icos/20.1.0?topic=cplex-lp-file-format-algebraic-representation
